#!/bin/sh

REFRESH_URL=http://127.0.0.1:4667/auth/api-key-token \
TRANSFORM_URL=https://scaler-sign.matejukmar.workers.dev/sign \
UPLOAD_URI=atest/test-image3.jpeg \
API_KEY=API_KEY \
ts-node tests/testToBuffer.ts

